import { Link, useParams } from "react-router-dom";
import type { ReactNode } from "react-dom/client";
import { ArrowRight, CheckCircle2, CircleDashed, ExternalLink } from "lucide-react";

function Frame({ eyebrow, title, description, children, links=[] }: { eyebrow:string; title:string; description:string; children?:ReactNode; links?:{label:string;href:string}[] }) {
  return <div className="resource-page">
    <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></div>
    <div className="detail-layout">
      <main className="surface detail-main">{children}</main>
      {links.length > 0 && <aside className="surface detail-nav"><span className="eyebrow">RELATED</span>{links.map(l=><Link key={l.href} to={l.href}>{l.label}<ArrowRight size={15}/></Link>)}</aside>}
    </div>
  </div>;
}
function Empty({title="No live data returned yet.",text="This surface is ready for the control-plane response. No operational state is being fabricated while the backend contract is not connected."}:{title?:string;text?:string}) {
  return <div className="detail-empty"><CircleDashed size={22}/><strong>{title}</strong><span>{text}</span></div>;
}
export function SecurityTenantIsolation(){return <Frame eyebrow="SECURITY / TENANT ISOLATION" title="Tenant isolation boundary" description="Inspect how Proxima represents and verifies the isolation boundary." links={[{label:"Verification evidence",href:"/app/verification"},{label:"Security events",href:"/app/security/events"},{label:"Policies",href:"/app/policies"}]}><div className="detail-status"><CheckCircle2 size={19}/><strong>Awaiting live control-plane state</strong></div><Empty text="When connected, this view will show tenant context decisions, enforcement state and evidence for allowed and blocked paths."/></Frame>}
export function SecurityEvents(){return <Frame eyebrow="SECURITY / EVENTS" title="Security events" description="Investigate blocked requests, invalid context and policy security events." links={[{label:"Tenant isolation",href:"/app/security/tenant-isolation"},{label:"Audit stream",href:"/app/audit"}]}><Empty title="No security events returned yet." text="Real security events will appear here from the control plane, with links into their related tenant, policy, request and verification evidence."/></Frame>}
export function TenantDetail(){const {tenantId}=useParams();return <Frame eyebrow="TENANTS / DETAIL" title="Tenant" description="Inspect one tenant's protection boundary, policy and verification history." links={[{label:"All tenants",href:"/app/tenants"},{label:"Verification",href:"/app/verification"},{label:"Policies",href:"/app/policies"}]}><div className="resource-identity"><span>Tenant ID</span><strong>{tenantId}</strong></div><Empty text="The selected tenant will show its real protection state, environment, node, policy and verification history when returned by the control plane."/></Frame>}
export function PolicyDetail(){const {policyId}=useParams();return <Frame eyebrow="POLICIES / DETAIL" title="Policy" description="Inspect enforcement rules, versions, deployment history and verification results." links={[{label:"All policies",href:"/app/policies"},{label:"Deployments",href:"/app/deployments"},{label:"Verification",href:"/app/verification"}]}><div className="resource-identity"><span>Policy ID</span><strong>{policyId}</strong></div><Empty text="Policy definition, version history, author, environment and deployment state will come from the control plane."/></Frame>}
export function NodeDetail(){const {nodeId}=useParams();return <Frame eyebrow="INFRASTRUCTURE / NODE" title="Node" description="Inspect enforcement infrastructure, health, tenants and deployment state." links={[{label:"Node inventory",href:"/app/nodes"},{label:"Deployments",href:"/app/deployments"}]}><div className="resource-identity"><span>Node ID</span><strong>{nodeId}</strong></div><Empty text="Node health, region, version, heartbeat, assigned tenants and topology relationships will be populated from real infrastructure state."/></Frame>}
export function DeploymentDetail(){const {deploymentId}=useParams();return <Frame eyebrow="DEPLOYMENTS / DETAIL" title="Deployment" description="Trace one deployment from release through policy changes and verification." links={[{label:"Deployment history",href:"/app/deployments"},{label:"Policies",href:"/app/policies"},{label:"Verification",href:"/app/verification"}]}><div className="resource-identity"><span>Deployment ID</span><strong>{deploymentId}</strong></div><Empty text="Release metadata, affected nodes, policy changes, actor, timeline and verification outcome will be sourced from the control plane."/></Frame>}
export function VerificationDetail(){const {runId}=useParams();return <Frame eyebrow="VERIFICATION / EVIDENCE" title="Verification run" description="Inspect the evidence behind an isolation decision." links={[{label:"Verification history",href:"/app/verification"},{label:"Audit stream",href:"/app/audit"},{label:"Security",href:"/app/security"}]}><div className="resource-identity"><span>Run ID</span><strong>{runId}</strong></div><Empty title="No verification evidence returned yet." text="The evidence view will expose tenant context, source, destination, policy, decision, timestamp, node and verification metadata from the real verification system."/></Frame>}
export function AuditEvent(){const {eventId}=useParams();return <Frame eyebrow="AUDIT / EVENT" title="Audit event" description="Inspect the complete evidence record for one control-plane event." links={[{label:"Audit stream",href:"/app/audit"},{label:"Verification",href:"/app/verification"},{label:"Security",href:"/app/security"}]}><div className="resource-identity"><span>Event ID</span><strong>{eventId}</strong></div><Empty title="No event record returned yet." text="Actor, tenant, event type, timestamp, environment, request ID and related resources will be shown from the real audit stream."/></Frame>}
export function TeamMember(){const {memberId}=useParams();return <Frame eyebrow="TEAM / MEMBER" title="Team member" description="Inspect organization membership, role and access." links={[{label:"Team",href:"/app/team"},{label:"Invitations",href:"/app/team/invitations"},{label:"Roles",href:"/app/team/roles"}]}><div className="resource-identity"><span>Member ID</span><strong>{memberId}</strong></div><Empty title="No member record returned yet." text="Membership and permissions will be loaded from the organization control-plane APIs."/></Frame>}
export function TeamInvitations(){return <Frame eyebrow="TEAM / INVITATIONS" title="Invitations" description="Manage pending invitations to the organization." links={[{label:"Team members",href:"/app/team"},{label:"Roles",href:"/app/team/roles"}]}><Empty title="No invitation data returned yet." text="This surface is reserved for the existing organization invitation backend and will not invent pending members."/></Frame>}
export function TeamRoles(){return <Frame eyebrow="TEAM / ROLES" title="Roles and permissions" description="Inspect workspace roles and the permissions assigned to them." links={[{label:"Team members",href:"/app/team"},{label:"Settings",href:"/app/settings"}]}><Empty title="No role data returned yet." text="Role definitions and effective permissions will come from the organization authorization model."/></Frame>}
export function BillingUsage(){return <Frame eyebrow="BILLING / USAGE" title="Usage" description="Inspect metered platform usage for the current billing period." links={[{label:"Plans",href:"/app/billing/plans"},{label:"Invoices",href:"/app/billing/invoices"}]}><Empty title="No usage telemetry returned yet." text="Usage charts and period totals will be populated from billing data once the billing backend is connected."/></Frame>}
export function BillingPlans(){return <Frame eyebrow="BILLING / PLANS" title="Plans" description="Compare available Agata plans and the capabilities associated with each plan." links={[{label:"Usage",href:"/app/billing/usage"},{label:"Invoices",href:"/app/billing/invoices"}]}><div className="plan-list"><div><strong>Free</strong><span>Evaluation and local development</span></div><div><strong>Starter</strong><span>Production tenant protection</span></div><div><strong>Growth</strong><span>Advanced operations and verification</span></div><div><strong>Scale</strong><span>Larger production environments</span></div><div><strong>Enterprise</strong><span>Custom identity, security and commercial requirements</span></div></div></Frame>}
export function BillingInvoices(){return <Frame eyebrow="BILLING / INVOICES" title="Invoices" description="Review billing documents and payment history." links={[{label:"Usage",href:"/app/billing/usage"},{label:"Plans",href:"/app/billing/plans"}]}><Empty title="No invoices available yet." text="Invoices will appear here when the billing system has generated them for this workspace."/></Frame>}
export function DeveloperArea(){return <Frame eyebrow="DEVELOPER" title="Developer platform" description="Connect an application to Proxima through authentication, tenant context, APIs and operational events." links={[{label:"Authentication",href:"/app/developer/authentication"},{label:"Tenant context",href:"/app/developer/tenant-context"},{label:"API keys",href:"/app/developer/api-keys"},{label:"API reference",href:"/app/developer/api-reference"}]}><div className="integration-path"><div><span>01</span><strong>Authenticate</strong><p>Establish the application identity that is allowed to communicate with Proxima.</p></div><div><span>02</span><strong>Attach tenant context</strong><p>Carry an explicit tenant identity through the protected request path.</p></div><div><span>03</span><strong>Enforce</strong><p>Send protected operations through the Proxima enforcement boundary.</p></div><div><span>04</span><strong>Verify</strong><p>Exercise the boundary and inspect the resulting evidence.</p></div></div></Frame>}
export function DeveloperApiKeys(){return <Frame eyebrow="DEVELOPER / API KEYS" title="API keys" description="Manage credentials used by applications and automation." links={[{label:"Authentication",href:"/app/developer/authentication"},{label:"Service accounts",href:"/app/developer/service-accounts"}]}><Empty title="No API credentials available yet." text="Credential creation and rotation will be connected to the authentication backend before this surface is considered operational."/></Frame>}
export function DeveloperServiceAccounts(){return <Frame eyebrow="DEVELOPER / SERVICE ACCOUNTS" title="Service accounts" description="Manage non-human identities used by infrastructure and automation." links={[{label:"API keys",href:"/app/developer/api-keys"},{label:"Authentication",href:"/app/developer/authentication"}]}><Empty title="No service accounts returned yet." text="Service-account lifecycle operations will be wired to the control plane before they become active."/></Frame>}
export function DeveloperAuthentication(){return <Frame eyebrow="DEVELOPER / AUTHENTICATION" title="Authentication" description="Understand how application identity enters the Proxima request path." links={[{label:"Tenant context",href:"/app/developer/tenant-context"},{label:"Enterprise identity",href:"/app/settings/identity"}]}><div className="integration-code"><code>Identity → authenticated request → tenant context → Proxima</code></div><Empty text="Provider configuration and credential state will be loaded from the real authentication service."/></Frame>}
export function DeveloperTenantContext(){return <Frame eyebrow="DEVELOPER / TENANT CONTEXT" title="Tenant context" description="Integrate explicit tenant identity into protected application requests." links={[{label:"Authentication",href:"/app/developer/authentication"},{label:"Verification",href:"/app/verification"}]}><div className="integration-path"><div><span>01</span><strong>Resolve tenant</strong><p>Identify the tenant associated with the authenticated request.</p></div><div><span>02</span><strong>Bind context</strong><p>Attach tenant context to the request before protected access.</p></div><div><span>03</span><strong>Verify boundary</strong><p>Confirm tenant-local operations succeed and cross-tenant operations are blocked.</p></div></div></Frame>}
export function DeveloperWebhooks(){return <Frame eyebrow="DEVELOPER / WEBHOOKS" title="Webhooks" description="Connect Proxima events to your existing engineering and security systems." links={[{label:"Events",href:"/app/developer/events"},{label:"API reference",href:"/app/developer/api-reference"}]}><Empty title="No webhook endpoints configured." text="Endpoint registration, delivery state and signing configuration will be backed by the events system."/></Frame>}
export function DeveloperEvents(){return <Frame eyebrow="DEVELOPER / EVENTS" title="Events" description="Inspect events exposed to integrations and automation." links={[{label:"Webhooks",href:"/app/developer/webhooks"},{label:"Audit",href:"/app/audit"}]}><Empty title="No integration events returned yet." text="Events will be populated from the control-plane event stream."/></Frame>}
export function DeveloperEnvironments(){return <Frame eyebrow="DEVELOPER / ENVIRONMENTS" title="Environments" description="Separate development, staging and production integration boundaries." links={[{label:"Settings",href:"/app/settings/environments"},{label:"Tenant context",href:"/app/developer/tenant-context"}]}><Empty title="No environments returned yet." text="Environment records will be loaded from workspace configuration."/></Frame>}
export function DeveloperSdks(){return <Frame eyebrow="DEVELOPER / SDKS" title="SDKs" description="Choose the supported integration surface for your application." links={[{label:"API reference",href:"/app/developer/api-reference"},{label:"CLI",href:"/app/developer/cli"},{label:"Terraform",href:"/app/developer/terraform"}]}><div className="sdk-list"><strong>SDK availability</strong><span>Installation commands and package versions will be published here when the SDK artifacts are connected.</span></div></Frame>}
export function DeveloperCli(){return <Frame eyebrow="DEVELOPER / CLI" title="CLI" description="Operate Proxima from engineering workflows and automation." links={[{label:"SDKs",href:"/app/developer/sdks"},{label:"API reference",href:"/app/developer/api-reference"}]}><div className="integration-code"><code>proxima &lt;command&gt;</code></div><Empty title="CLI commands are not connected yet." text="The command surface will be backed by the published CLI contract rather than placeholder actions."/></Frame>}
export function DeveloperTerraform(){return <Frame eyebrow="DEVELOPER / TERRAFORM" title="Terraform" description="Manage supported Proxima infrastructure as code." links={[{label:"Environments",href:"/app/developer/environments"},{label:"API reference",href:"/app/developer/api-reference"}]}><Empty title="Terraform provider not connected yet." text="Provider resources and examples will appear when the infrastructure-as-code contract is available."/></Frame>}
export function DeveloperApiReference(){return <Frame eyebrow="DEVELOPER / API REFERENCE" title="API reference" description="Explore the contracts exposed by the Proxima control plane." links={[{label:"Authentication",href:"/app/developer/authentication"},{label:"Tenant context",href:"/app/developer/tenant-context"}]}><div className="api-surface"><strong>Control-plane API</strong><span>Endpoint documentation will be generated from the authoritative backend contract when the API surface is connected.</span></div></Frame>}
export function SettingsArea(){return <Frame eyebrow="SETTINGS" title="Workspace settings" description="Configure organization-wide behavior, access, identity and security." links={[{label:"Members",href:"/app/settings/members"},{label:"Authentication",href:"/app/settings/authentication"},{label:"Enterprise identity",href:"/app/settings/identity"},{label:"Security",href:"/app/settings/security"}]}><Empty title="No workspace configuration returned yet." text="Settings are ready for the authenticated organization and environment APIs."/></Frame>}
export function SettingsMembers(){return <Frame eyebrow="SETTINGS / MEMBERS" title="Members and roles" description="Manage workspace access and organization membership." links={[{label:"Team",href:"/app/team"},{label:"Roles",href:"/app/team/roles"}]}><Empty title="No member configuration returned yet." text="This surface will use the same organization membership model as the Team area."/></Frame>}
export function SettingsAuthentication(){return <Frame eyebrow="SETTINGS / AUTHENTICATION" title="Authentication settings" description="Configure workspace authentication requirements and access behavior." links={[{label:"Enterprise identity",href:"/app/settings/identity"},{label:"Developer authentication",href:"/app/developer/authentication"}]}><Empty title="No authentication configuration returned yet." text="Provider and policy settings will be loaded from the authenticated workspace."/></Frame>}
export function SettingsIdentity(){return <Frame eyebrow="SETTINGS / ENTERPRISE IDENTITY" title="Enterprise identity" description="Configure enterprise identity and organization sign-in controls." links={[{label:"Authentication settings",href:"/app/settings/authentication"},{label:"Developer authentication",href:"/app/developer/authentication"}]}><Empty title="No identity provider configured." text="OIDC and enterprise identity belong here once the identity backend is connected."/></Frame>}
export function SettingsSecurity(){return <Frame eyebrow="SETTINGS / SECURITY" title="Security settings" description="Configure security controls for the workspace and its members." links={[{label:"Security posture",href:"/app/security"},{label:"Authentication",href:"/app/settings/authentication"}]}><Empty title="No security configuration returned yet." text="Security configuration will be sourced from the workspace control plane."/></Frame>}
export function SettingsEnvironments(){return <Frame eyebrow="SETTINGS / ENVIRONMENTS" title="Environments" description="Manage workspace environment boundaries." links={[{label:"Developer environments",href:"/app/developer/environments"},{label:"Settings",href:"/app/settings"}]}><Empty title="No environment configuration returned yet." text="Environment creation and configuration will use real workspace data."/></Frame>}
export function SettingsNotifications(){return <Frame eyebrow="SETTINGS / NOTIFICATIONS" title="Notifications" description="Control operational and security notifications." links={[{label:"Security",href:"/app/security"},{label:"Support",href:"/app/support"}]}><Empty title="No notification configuration returned yet." text="Notification preferences will be stored against the authenticated workspace."/></Frame>}
export function SettingsDanger(){return <Frame eyebrow="SETTINGS / DANGER ZONE" title="Danger Zone" description="Irreversible workspace operations require explicit confirmation." links={[{label:"Workspace settings",href:"/app/settings"}]}><div className="danger-surface"><strong>Destructive operations are disabled.</strong><span>No destructive action is exposed until the authenticated backend contract and confirmation flow are implemented.</span></div></Frame>}
