import { useEffect, useState, type FormEvent } from "react";
import { RefreshCw, RotateCw, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../../api/client";

type Integration={id:string;name:string;status:string;mode:string;configuration:Record<string,unknown>;created_at:string};
type EnvironmentCredential={id:string;integration_id:string;environment_id:string;environment:string;key_prefix:string;active:boolean;created_at:string};
type Environment={id:string;key:string;name:string;mode:string;status:string;deployment_state:string;verification_state:string;bypass_until?:string|null};
type DbConnection={id:string;environment_id:string;environment:string;host:string;port:number;database:string;username:string;tls_mode:string;status:string;last_health_at?:string|null;last_error?:string|null};

export function Integrations(){const [items,setItems]=useState<Integration[]>([]);const [credentials,setCredentials]=useState<EnvironmentCredential[]>([]);const [envs,setEnvs]=useState<Environment[]>([]);const [name,setName]=useState("");const [environmentId,setEnvironmentId]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [revealedSecret,setRevealedSecret]=useState("");const [revealedEnvironment,setRevealedEnvironment]=useState("");const [copied,setCopied]=useState(false);
 async function load(){try{const [integrations,environmentCredentials,environments]=await Promise.all([api.get<Integration[]>("/api/v1/integrations"),api.get<EnvironmentCredential[]>("/api/v1/integration-environment-credentials"),api.get<Environment[]>("/api/v1/environments")]);setItems(integrations);setCredentials(environmentCredentials);setEnvs(environments);setEnvironmentId(v=>v||environments.find(e=>e.key==="staging")?.id||environments[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Unable to load integrations.")}} useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{await api.post("/api/v1/integrations",{name});setName("");setMessage("Integration created. Now issue an environment credential for the environment that will run the customer application.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create integration.")}finally{setBusy(false)}}
 async function credential(id:string){setError("");setMessage("");setCopied(false);if(!environmentId){setError("Select an environment before issuing an environment credential.");return}try{const r=await api.post<{credential:string}>("/api/v1/integrations/"+id+"/environments/"+environmentId+"/credentials",{});setRevealedSecret(r.credential);setRevealedEnvironment(envs.find(e=>e.id===environmentId)?.name||environmentId);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to issue environment credential.")}}
 async function act(path:string){setError("");setMessage("");try{await api.post(path,{});setMessage("Integration updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Integration action failed.")}}\n async function credentialAction(path:string,environmentName:string){setError("");setMessage("");setCopied(false);try{const result=await api.post<{credential:string}>(path,{});setRevealedSecret(result.credential);setRevealedEnvironment(environmentName);await load()}catch(e){setError(e instanceof Error?e.message:"Credential action failed.")}}\n async function copySecret(){try{await navigator.clipboard.writeText(revealedSecret);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setError("Clipboard access was blocked. Copy the credential manually before hiding it.")}}
 return <div className="resource-page"><div className="page-heading"><div><span className="eyebrow">INTEGRATIONS</span><h1>Customer integrations</h1><p>Manage organization-owned integrations, credentials, lifecycle state and enforcement mode.</p></div><button className="console-refresh-button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>{message&&<div className="settings-banner">{message}</div>}{error&&<div className="settings-banner settings-banner--error">{error}</div>}
 <div className="resource-section-grid"><section className="surface"><span className="eyebrow">CREATE INTEGRATION</span><h2>Connect a customer application</h2><p>Agata provides the tenant, policy, verification and enforcement boundary while the customer keeps its application and authorization logic.</p><form className="settings-form" onSubmit={create}><label>Integration name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Customer application"/></label><button className="primary-action" disabled={busy}>{busy?"Creating…":"Create integration"}</button></form></section>
 <section className="surface"><span className="eyebrow">ENVIRONMENT CREDENTIAL</span><h2>Issue customer connection credentials</h2><p>Credentials are scoped to one integration and one environment. The secret is shown once and then only its hash and prefix remain.</p><label>Environment<select value={environmentId} onChange={e=>setEnvironmentId(e.target.value)}>{envs.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label></section></div>
 <div className="secret-reveal integration-secret-reveal"><span>ENVIRONMENT CREDENTIAL · {revealedEnvironment||"Selected environment"}</span><strong>Copy this credential now. It will not be shown again after you hide this panel.</strong><code>{revealedSecret||"—"}</code><div className="secret-reveal-actions"><button onClick={()=>void copySecret()}><span>{copied?"Copied":"Copy credential"}</span></button><button className="secret-dismiss" onClick={()=>{setRevealedSecret("");setRevealedEnvironment("");setCopied(false)}}>I copied it — hide</button></div></div><section className="surface"><div className="panel-heading"><div><strong>Integrations</strong><span>{items.length} organization-owned integration{items.length===1?"":"s"}</span></div></div><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Name</th><th>Status</th><th>Mode</th><th>Created</th><th>Actions</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>Environment credentials are managed separately below.</small></td><td>{i.status}</td><td>{i.mode}</td><td>{new Date(i.created_at).toLocaleString()}</td><td>{i.status==="active"&&<><button className="console-secondary-button" onClick={()=>void credential(i.id)}>Issue credential</button><button className="console-secondary-button" onClick={()=>void act("/api/v1/integrations/"+i.id+"/deactivate")}>Deactivate</button></>}</td></tr>)}</tbody></table></div></section>
 <section className="surface"><div className="panel-heading"><div><strong>Environment credentials</strong><span>One credential per integration and environment. Only the prefix remains visible after creation.</span></div></div><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Environment</th><th>Integration</th><th>Prefix</th><th>Status</th><th>Actions</th></tr></thead><tbody>{credentials.map(c=>{const integration=items.find(i=>i.id===c.integration_id);return <tr key={c.id}><td>{c.environment}</td><td>{integration?.name||c.integration_id}</td><td><code>{c.key_prefix}…</code></td><td>{c.active?"Active":"Revoked"}</td><td>{c.active&&<><button className="console-secondary-button" onClick={()=>void credentialAction("/api/v1/integrations/"+c.integration_id+"/environments/"+c.environment_id+"/credentials/rotate",c.environment)}><RotateCw size={14}/> Rotate</button><button className="console-secondary-button" onClick={()=>void act("/api/v1/integrations/"+c.integration_id+"/environments/"+c.environment_id+"/credentials/revoke")}>Revoke</button></>}</td></tr>})}</tbody></table></div></section>
 <div className="context-next"><Link to="/app/environments">Open environments</Link><Link to="/app/database">Open database connections</Link><Link to="/app/developer/tenant-context">Tenant context contract</Link></div></div>}

export function Environments(){const [items,setItems]=useState<Environment[]>([]);const [message,setMessage]=useState("");const [error,setError]=useState("");
 async function load(){try{setItems(await api.get<Environment[]>("/api/v1/environments"))}catch(e){setError(e instanceof Error?e.message:"Unable to load environments.")}}useEffect(()=>{void load()},[]);
 async function mode(id:string,mode:string){setError("");try{await api.patch("/api/v1/environments/"+id+"/mode",{mode});setMessage("Environment mode updated.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update environment mode.")}}
 async function bypass(id:string){const reason=window.prompt("Enter the audited emergency-bypass reason:","Controlled production recovery");if(!reason)return;try{const r=await api.post<{expires_at:string}>("/api/v1/environments/"+id+"/bypass",{reason,duration_seconds:900});setMessage("Emergency maintenance mode authorized until "+new Date(r.expires_at).toLocaleString());await load()}catch(e){setError(e instanceof Error?e.message:"Unable to authorize emergency mode.")}}
 return <div className="resource-page"><div className="page-heading"><div><span className="eyebrow">ENVIRONMENTS</span><h1>Development, staging and production</h1><p>Each environment has its own identity, mode, deployment state, verification state and database boundary.</p></div><button className="console-refresh-button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>{message&&<div className="settings-banner">{message}</div>}{error&&<div className="settings-banner settings-banner--error">{error}</div>}<section className="surface"><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Environment</th><th>Mode</th><th>Status</th><th>Deployment</th><th>Verification</th><th>Controls</th></tr></thead><tbody>{items.map(e=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.key}</small></td><td><select value={e.mode} onChange={x=>void mode(e.id,x.target.value)}><option value="development">Development</option><option value="shadow">Shadow</option><option value="enforcement">Enforcement</option><option value="maintenance">Maintenance</option></select></td><td>{e.status}</td><td>{e.deployment_state}</td><td>{e.verification_state}</td><td><button className="console-secondary-button" onClick={()=>void bypass(e.id)}>Emergency maintenance</button></td></tr>)}</tbody></table></div></section><div className="context-next"><Link to="/app/integrations">Integrations</Link><Link to="/app/database">Database connections</Link><Link to="/app/developer/environments">Developer environment contract</Link></div></div>}

export function DatabaseConnections(){const [items,setItems]=useState<DbConnection[]>([]);const [envs,setEnvs]=useState<Environment[]>([]);const [form,setForm]=useState({environment_id:"",host:"",port:"5432",database_name:"",username:"",password:"",tls_mode:"require"});const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function load(){try{const [d,e]=await Promise.all([api.get<DbConnection[]>("/api/v1/database-connections"),api.get<Environment[]>("/api/v1/environments")]);setItems(d);setEnvs(e);setForm(v=>({...v,environment_id:v.environment_id||e.find(x=>x.key==="staging")?.id||e[0]?.id||""}))}catch(e){setError(e instanceof Error?e.message:"Unable to load database connections.")}}useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await api.post<{ok:boolean;status:string;error?:string}>("/api/v1/database-connections",{...form,port:Number(form.port)});setMessage(r.ok?"Database connected and health check passed.":"Database configuration stored with status "+r.status+(r.error?" — "+r.error:""));setForm(v=>({...v,password:""}));await load()}catch(e){setError(e instanceof Error?e.message:"Unable to configure database connection.")}finally{setBusy(false)}}
 async function validate(id:string){try{const r=await api.post<{ok:boolean;status:string;message?:string}>("/api/v1/database-connections/"+id+"/validate",{});setMessage(r.ok?"Database health check passed.":"Database health check failed: "+(r.message||r.status));await load()}catch(e){setError(e instanceof Error?e.message:"Database validation failed.")}}
 return <div className="resource-page"><div className="page-heading"><div><span className="eyebrow">POSTGRESQL</span><h1>Environment database connections</h1><p>Customer database credentials are encrypted at rest with the deployment secret and are never returned by the API.</p></div><button className="console-refresh-button" onClick={()=>void load()}><RefreshCw size={15}/> Refresh</button></div>{message&&<div className="settings-banner">{message}</div>}{error&&<div className="settings-banner settings-banner--error">{error}</div>}
 <section className="surface"><span className="eyebrow">CONFIGURE</span><h2>Validate a PostgreSQL boundary</h2><form className="settings-form" onSubmit={save}><label>Environment<select required value={form.environment_id} onChange={e=>setForm({...form,environment_id:e.target.value})}>{envs.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Host<input required value={form.host} onChange={e=>setForm({...form,host:e.target.value})}/></label><label>Port<input required type="number" min="1" max="65535" value={form.port} onChange={e=>setForm({...form,port:e.target.value})}/></label><label>Database<input required value={form.database_name} onChange={e=>setForm({...form,database_name:e.target.value})}/></label><label>Username<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>TLS<select value={form.tls_mode} onChange={e=>setForm({...form,tls_mode:e.target.value})}><option value="require">require</option><option value="verify-full">verify-full</option><option value="verify-ca">verify-ca</option><option value="disable">disable (local only)</option></select></label><button className="primary-action" disabled={busy}>{busy?"Validating…":"Save and validate"}</button></form></section>
 <section className="surface"><div className="panel-heading"><div><strong>Configured boundaries</strong><span>{items.length} environment connection{items.length===1?"":"s"}</span></div></div><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>Environment</th><th>Host</th><th>Database</th><th>TLS</th><th>Status</th><th>Health</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.environment}</td><td>{i.host}:{i.port}</td><td>{i.database}</td><td>{i.tls_mode}</td><td>{i.status}</td><td><button className="console-secondary-button" onClick={()=>void validate(i.id)}><ShieldCheck size={14}/> Validate</button></td></tr>)}</tbody></table></div></section></div>}
