import { Link, useParams } from "react-router-dom";
import type { ReactNode } from "react";

const Pill = ({ children }: { children: ReactNode }) => <span className="public-pill">{children}</span>;

function PageHeader({ eyebrow, title, intro }: { eyebrow: string; title: string; intro: string }) {
  return (
    <header className="public-page-header">
      <Pill>{eyebrow}</Pill>
      <h1>{title}</h1>
      <p>{intro}</p>
    </header>
  );
}

function Section({ eyebrow, title, children, dark = false }: { eyebrow?: string; title: string; children: ReactNode; dark?: boolean }) {
  return <section className={`public-section ${dark ? "public-section-dark" : ""}`}>
    <div className="public-container">
      {eyebrow && <div className="public-eyebrow">{eyebrow}</div>}
      <h2>{title}</h2>
      <div className="public-section-content">{children}</div>
    </div>
  </section>;
}

const Architecture = () => (
  <div className="architecture-flow">
    {[
      ["01", "Application", "Your product makes a tenant-aware request."],
      ["02", "Tenant Context", "The request carries the tenant identity that should govern access."],
      ["03", "Proxima", "The enforcement boundary evaluates the request before protected data is reached."],
      ["04", "PostgreSQL", "Database-level controls provide a second enforcement layer."],
      ["05", "Verification", "The system tests whether isolation actually holds."],
      ["06", "Evidence", "The result becomes inspectable evidence instead of an assumption."],
    ].map(([n, title, text], i) => <div className="architecture-step" key={title}>
      <span>{n}</span><div><strong>{title}</strong><p>{text}</p></div>{i < 5 && <b>→</b>}
    </div>)}
  </div>
);

export function Home() {
  return <>
    <main className="public-home">
      <section className="home-hero public-container">
        <div className="hero-copy">
          <Pill>Tenant isolation infrastructure</Pill>
          <h1>Make tenant isolation an independently verifiable boundary.</h1>
          <p>Agata Proxima gives multi-tenant systems a dedicated enforcement and verification layer between application identity and protected data.</p>
          <div className="hero-actions"><Link className="button button-primary" to="/signup">Start building</Link><Link className="button button-secondary" to="/docs/getting-started">Read the guide</Link></div>
        </div>
        <div className="hero-architecture"><Architecture /></div>
      </section>
      <Section eyebrow="THE PROBLEM" title="Tenant isolation is a system property, not a convention.">
        <div className="three-columns">
          <article><span>01</span><h3>Identity is not enough.</h3><p>A user can be authenticated and still carry the wrong tenant context. Isolation has to survive the full request path.</p></article>
          <article><span>02</span><h3>Checks become scattered.</h3><p>When every service implements its own tenant checks, coverage becomes difficult to reason about and harder to verify.</p></article>
          <article><span>03</span><h3>Claims need evidence.</h3><p>A secure design should be testable. Proxima turns isolation decisions and verification results into inspectable evidence.</p></article>
        </div>
      </Section>
      <Section eyebrow="THE BOUNDARY" title="One request path. One isolation decision.">
        <div className="decision-layout">
          <div><Architecture /></div>
          <div className="decision-panel"><div className="decision allow"><span>ALLOW</span><strong>A → A</strong><p>Request tenant matches protected tenant.</p></div><div className="decision block"><span>BLOCK</span><strong>A → B</strong><p>Request attempts to cross the tenant boundary.</p></div><div className="decision block"><span>BLOCK</span><strong>Expired context</strong><p>Tenant context is no longer valid for the request.</p></div></div>
        </div>
      </Section>
      <Section dark eyebrow="WHY PROXIMA" title="Separate enforcement from application convention.">
        <div className="dark-grid"><article><span>ENFORCE</span><h3>Put a boundary around tenant-aware access.</h3><p>Centralize the decision path so the application does not have to reinvent isolation checks in every feature.</p></article><article><span>VERIFY</span><h3>Test the property you actually care about.</h3><p>Verification exercises the isolation boundary and records whether expected allow and block behavior holds.</p></article><article><span>PROVE</span><h3>Keep evidence of the result.</h3><p>Evidence gives engineers and security teams something concrete to inspect when reviewing the state of isolation.</p></article></div>
      </Section>
      <Section eyebrow="WITHOUT / WITH" title="Move from scattered checks to a dedicated boundary.">
        <div className="compare"><div><h3>Without a dedicated boundary</h3><ul><li>Tenant checks spread across services.</li><li>Authorization and isolation become easy to conflate.</li><li>Failures are discovered late.</li><li>Security claims are difficult to demonstrate.</li></ul></div><div><h3>With Proxima</h3><ul><li>Tenant-aware requests pass through an explicit boundary.</li><li>Database enforcement participates in isolation.</li><li>Verification tests expected behavior.</li><li>Evidence records what was verified.</li></ul></div></div>
      </Section>
      <Section eyebrow="BUILD WITH IT" title="Designed for teams building multi-tenant infrastructure.">
        <div className="link-grid"><Link to="/solutions/b2b-saas"><strong>B2B SaaS</strong><span>Shared applications serving many customer organizations.</span></Link><Link to="/solutions/platform-engineering"><strong>Platform engineering</strong><span>Standardize isolation controls across internal services.</span></Link><Link to="/developers"><strong>Developer Platform</strong><span>Integrate tenant context, enforcement and verification into your stack.</span></Link><Link to="/docs"><strong>Documentation</strong><span>Understand the model and implement it step by step.</span></Link></div>
      </Section>
      <section className="home-cta public-container"><div><Pill>AGATA PROXIMA</Pill><h2>Build the boundary. Verify the boundary.</h2><p>Start with the architecture, then connect Proxima to the systems that need tenant isolation you can reason about.</p></div><Link className="button button-primary" to="/signup">Start building</Link></section>
    </main>
  </>;
}

const productPages: Record<string, { eyebrow: string; title: string; intro: string; sections: [string, string, string][] }> = {
  operating: { eyebrow: "PRODUCT / OPERATING MODEL", title: "A dedicated path for tenant-aware access.", intro: "Proxima separates tenant context, enforcement, database isolation, verification and evidence into an understandable operating model.", sections: [["The request path", "From application to evidence", "A tenant-aware request is evaluated as it moves through identity, tenant context, the Proxima boundary, protected storage and verification. Each layer has a defined responsibility."],["Identity", "Know who is making the request.", "Authentication establishes the principal. It does not by itself prove that the principal is accessing the correct tenant."],["Tenant context", "Make tenant identity explicit.", "Tenant context carries the tenant decision through the request path so downstream enforcement can evaluate the intended scope."],["Evidence", "Make isolation inspectable.", "Verification results and audit information provide an operational record of what the system checked and what it decided."]] },
  enforcement: { eyebrow: "PRODUCT / ENFORCEMENT", title: "Enforcement belongs at the boundary.", intro: "Proxima turns tenant-aware access into an explicit allow or block decision before protected data is reached.", sections: [["Decision model", "Allow what belongs. Block what crosses.", "A request for tenant A should remain within tenant A. A request attempting to use tenant A credentials against tenant B data is a boundary violation and should be blocked."],["Database layer", "Defense in depth with PostgreSQL.", "Application-level enforcement is complemented by database controls so a single missed application check does not become the only line of defense."],["Invalid context", "Fail closed when context cannot be trusted.", "Expired or invalid tenant context should not silently degrade into an unscoped request. The safe outcome is a block and an inspectable failure."],["Operational result", "Turn decisions into evidence.", "Enforcement events can be reviewed alongside verification results so teams can understand what happened rather than relying on logs scattered across services."]] },
  verification: { eyebrow: "PRODUCT / VERIFICATION", title: "Verify the isolation property, not just the configuration.", intro: "Verification is the mechanism that tests whether the boundary behaves as intended.", sections: [["Expected behavior", "Define the decisions first.", "Verification begins with explicit expected outcomes: same-tenant requests are allowed; cross-tenant requests and invalid context are blocked."],["Attack paths", "Exercise failure modes.", "A useful verification run probes the paths that matter: wrong tenant context, expired context, mismatched identity and protected-resource access."],["Result", "Make the outcome reviewable.", "A verification result should explain what was tested, what happened, and where a failure occurred so an engineer can investigate it."],["Evidence", "Keep a durable record.", "The purpose of verification is not only to pass a test once. The result should become evidence that can be inspected during operations and security review."]] },
  evidence: { eyebrow: "PRODUCT / EVIDENCE", title: "Security claims should have something behind them.", intro: "Evidence connects enforcement and verification to the operational record engineers and security teams can inspect.", sections: [["What evidence means", "A record of a decision or verification result.", "Evidence describes what the system evaluated and what result it produced. It gives teams a concrete object to inspect when investigating isolation."],["Auditability", "Trace important events.", "Tenant-aware decisions, verification outcomes and relevant operational events should be discoverable without reconstructing the story from unrelated service logs."],["Security review", "Make review less subjective.", "Evidence helps a reviewer move from a design statement to an observable result: what was tested, when it ran and whether the expected boundary held."],["Operations", "Use evidence during incidents.", "When a request is unexpectedly blocked or a verification run fails, the evidence trail becomes part of the diagnostic path."]] },
};

export function Product() { return <MarketingPage eyebrow="PRODUCT" title="Tenant isolation infrastructure for systems that need an enforceable boundary." intro="Agata Proxima combines tenant context, enforcement, PostgreSQL isolation, verification and evidence into one operating model." links={["/product/operating-model","/product/enforcement","/product/verification","/product/evidence"]} />; }
export function ProductDetail({ kind }: { kind: keyof typeof productPages }) { const p = productPages[kind]; return <ArticlePage {...p} />; }

const solutionPages: Record<string, { title: string; intro: string; sections: [string,string,string][] }> = {
  "b2b-saas": { title:"B2B SaaS", intro:"Keep customer data isolated as one application serves many organizations.", sections:[["The problem","Shared infrastructure creates shared failure modes.","Tenant identifiers appear throughout requests, queries and background work. A single missing check can expose data across customers."],["The Proxima model","Make tenant scope explicit.","Route tenant-aware access through an enforcement boundary and complement it with database-level isolation."],["Operational value","Know what happened.","Verification and evidence give engineering teams a way to test isolation and investigate failures without depending on assumptions."]] },
  "enterprise-saas": { title:"Enterprise SaaS", intro:"Give enterprise workloads a stronger isolation model and a clearer security story.", sections:[["Security architecture","Separate identity from tenant scope.","Enterprise identity can establish who a user is while Proxima governs which tenant scope the request is permitted to reach."],["Verification","Test the boundary continuously.","Use explicit allow and block expectations to verify that tenant isolation continues to hold as services evolve."],["Evidence","Support technical review.","Keep verification and enforcement results available for engineering, security and operational review."]] },
  "developer-platforms": { title:"Developer platforms", intro:"Provide tenant-aware infrastructure primitives without forcing every team to reinvent isolation.", sections:[["Platform primitive","Make the safe path the standard path.","A platform team can provide tenant context and enforcement as a shared capability instead of asking every product team to implement its own model."],["Integration","Meet developers where they work.","Expose clear authentication, context, verification and API concepts so teams can integrate without learning an unrelated security abstraction."],["Governance","Verify platform behavior.","Verification turns a platform promise into an observable property that can be tested across environments."]] },
  "security-sensitive-systems": { title:"Security-sensitive systems", intro:"Treat tenant boundaries as security controls that deserve explicit verification.", sections:[["Threat model","Assume mistakes will happen.","Security-sensitive systems need protection against wrong tenant context, expired credentials, authorization mistakes and accidental cross-tenant access."],["Defense in depth","Do not rely on one check.","Combine request-level enforcement with database controls and verification so failure in one layer does not automatically become exposure."],["Evidence","Make the control inspectable.","Record enough context around verification and enforcement to support investigation and review."]] },
  startups: { title:"Startups", intro:"Build a strong tenant model before isolation logic becomes scattered across the codebase.", sections:[["Early architecture","Establish the boundary while the system is small.","A clear isolation model is easier to maintain when introduced before every service, query and background job grows its own tenant conventions."],["Developer velocity","Reduce repeated security decisions.","A shared boundary gives product engineers a consistent model for tenant-aware access while keeping the underlying architecture visible."],["Growth","Make the model scale with the product.","As organizations, services and environments grow, verification and evidence provide operational confidence that the isolation property still holds."]] },
  "platform-engineering": { title:"Platform engineering", intro:"Standardize tenant isolation as infrastructure instead of a collection of application conventions.", sections:[["Shared capability","Provide one model to many teams.","Platform teams can expose a common enforcement and verification path for services that need tenant-aware access."],["Controls","Make policy observable.","A platform control is more useful when engineers can inspect the decision model and verify expected outcomes."],["Operations","Support fleet-level confidence.","Verification results and evidence can become part of deployment and operational workflows as the platform expands."]] },
};
export function Solutions(){ return <MarketingPage eyebrow="SOLUTIONS" title="A tenant isolation boundary for the systems your teams are building." intro="Choose the operating model that matches your architecture, then use Proxima to make tenant scope enforceable and verifiable." links={Object.keys(solutionPages).map(k=>`/solutions/${k}`)} />; }
export function SolutionDetail({ kind }: { kind: keyof typeof solutionPages }) { return <ArticlePage eyebrow="SOLUTIONS" title={solutionPages[kind].title} intro={solutionPages[kind].intro} sections={solutionPages[kind].sections}/>; }

export function Pricing(){ return <><PageHeader eyebrow="PRICING" title="Start with the isolation capabilities your system needs." intro="Agata Proxima pricing is organized around the maturity and operational needs of the systems you are protecting."/><Section title="Plans"><div className="pricing-table">{[["Free","$0","Explore the model and build with the core concepts."],["Starter","$149 / month","For teams introducing a dedicated tenant isolation boundary."],["Growth","$499 / month","For growing systems that need stronger operational verification."],["Scale","$1,199 / month","For larger environments and teams operating Proxima as infrastructure."],["Enterprise","Custom","For organizations with enterprise requirements and procurement needs."]].map(([n,p,d])=><article key={n}><span>{n}</span><strong>{p}</strong><p>{d}</p><Link to="/contact">Talk to Agata →</Link></article>)}</div></Section><Section eyebrow="BEFORE YOU CHOOSE" title="Understand what you are buying."><div className="prose-wide"><p>Plans should map to the way your organization operates tenant isolation, verification, environments and support. We intentionally avoid inventing quotas or capabilities that are not defined by the product.</p><p>For current capability questions, contact the team or review the developer and documentation surfaces.</p><div className="inline-links"><Link to="/developers">Developer Platform</Link><Link to="/docs">Documentation</Link><Link to="/contact">Contact</Link></div></div></Section></>}

export function Security(){ return <><PageHeader eyebrow="SECURITY" title="Security architecture for tenant isolation." intro="Agata Proxima is built around a simple security premise: tenant isolation should be enforced, tested and inspectable."/><Section title="Security model"><div className="security-list">{[["Identity","Authentication establishes the principal; tenant scope is handled separately."],["Tenant context","Tenant identity travels explicitly through the request path."],["Enforcement","The boundary decides whether the request can reach protected tenant data."],["Database controls","PostgreSQL provides another enforcement layer."],["Verification","Expected allow/block behavior is tested rather than assumed."],["Evidence","Results become inspectable operational and security evidence."]].map(([a,b])=><article key={a}><strong>{a}</strong><p>{b}</p></article>)}</div></Section><Section eyebrow="THREAT MODEL" title="Design for the mistakes that cause isolation failures."><div className="three-columns"><article><h3>Wrong tenant context</h3><p>A request identifies the wrong tenant and attempts to cross the boundary.</p></article><article><h3>Expired context</h3><p>A context that should no longer authorize access is presented to the system.</p></article><article><h3>Missing enforcement</h3><p>A service path bypasses an application convention and reaches protected data without the expected tenant check.</p></article></div></Section><Section title="Responsible disclosure"><div className="prose-wide"><p>If you believe you have found a security issue, use the security contact path rather than publicly disclosing sensitive details.</p><Link className="text-link" to="/contact">Contact the security team →</Link></div></Section></>}

const developerPages: Record<string,{title:string;intro:string;sections:[string,string,string][]}> = {
  quickstart:{title:"Quickstart",intro:"Understand the integration path before connecting Proxima to your application.",sections:[["1. Identify the tenant","Decide what the tenant boundary means in your application.","Document the organization or customer identifier that should govern protected access."],["2. Establish identity","Authenticate the calling principal.","Authentication answers who is making the request. Keep that separate from the tenant scope the request is allowed to use."],["3. Carry tenant context","Make the intended tenant explicit.","The request path should contain enough context for the enforcement layer to evaluate the intended tenant."],["4. Verify","Exercise allow and block cases.","Verify same-tenant access and deliberately test cross-tenant and invalid-context paths."],["5. Inspect evidence","Review the result.","Use the resulting verification and audit information to understand what the system actually observed."]]},
  authentication:{title:"Authentication",intro:"Authentication establishes the principal. Proxima uses that identity as one input to tenant-aware enforcement.",sections:[["Separate concerns","Identity is not tenant scope.","Do not treat a successful login as proof that the request may access every tenant the user could potentially name."],["Session boundary","Keep authenticated access protected.","The customer control plane remains behind the existing authentication boundary. Public documentation and support never bypass it."],["Tenant decision","Evaluate the requested scope.","The authenticated principal and tenant context must produce an authorization decision that remains within the intended boundary."]]},
  "tenant-context":{title:"Tenant Context",intro:"Tenant context makes the tenant decision explicit instead of leaving it implicit in application conventions.",sections:[["Purpose","Carry tenant scope through the request path.","A request should make clear which tenant it intends to operate on so downstream enforcement can compare that scope with protected resources."],["Integrity","Do not trust an arbitrary tenant identifier.","Tenant context needs an integrity model so a caller cannot simply change a value and become another tenant."],["Failure","Invalid context must fail closed.","Expired, malformed or otherwise invalid context should result in a block rather than an unscoped fallback."]]},
  verification:{title:"Verification",intro:"Verification tests the property that tenant A cannot reach tenant B data.",sections:[["Expected cases","Define the contract.","Same-tenant requests should be allowed. Cross-tenant requests and expired context should be blocked."],["Negative testing","Test the dangerous paths.","Verification should deliberately attempt the requests that would expose an isolation weakness if the boundary were missing."],["Evidence","Keep the result.","A verification run should produce enough information to understand what was tested and whether the expected result occurred."]]},
  "api-reference":{title:"API Reference",intro:"A structured reference for the concepts and operations exposed by Proxima. Endpoint availability must match the deployed control-plane implementation.",sections:[["Authentication","Understand how callers establish identity.","Use the authentication model documented for the environment you are integrating with. Do not place secrets in browser code."],["Tenant-aware operations","Keep tenant scope explicit.","Operations that access protected tenant resources should identify the intended scope and be evaluated by the enforcement boundary."],["Errors","Treat blocks as security decisions.","A blocked request is not merely a generic failure. The client should surface enough information to diagnose the issue without leaking protected data."]]},
  webhooks:{title:"Webhooks",intro:"Use event delivery to connect Proxima decisions and lifecycle changes to your systems when webhook support is enabled.",sections:[["Event design","Know what an event represents.","Events should be treated as notifications about a state change or recorded result, not as a substitute for authoritative state."],["Verification","Validate incoming events.","Consumers should authenticate and validate event integrity before acting on a webhook."],["Retries","Design for repeated delivery.","Webhook consumers should be idempotent because network failures can cause a valid event to be delivered more than once."]]},
  sdks:{title:"SDKs",intro:"Use SDKs to keep integration conventions close to the language and runtime your application already uses.",sections:[["Installation","Choose the supported SDK for your environment.","Install the package using the package manager appropriate to your application and pin versions in production."],["Configuration","Keep credentials server-side.","API credentials and sensitive tenant-enforcement configuration should not be embedded in public browser bundles."],["Verification","Test your integration.","Use the verification model to prove that SDK calls preserve the intended tenant boundary."]]},
  cli:{title:"CLI",intro:"The Proxima CLI is intended to make developer and operational workflows reproducible from the terminal.",sections:[["Authentication","Use secure local credentials.","Keep local credentials outside source control and use environment-specific configuration."],["Commands","Prefer inspectable operations.","Commands should make it possible to inspect configuration, trigger supported workflows and retrieve results without hiding important state."],["Automation","Use CI carefully.","CI credentials should be scoped to the job and rotated according to your organization's security practices."]]},
  terraform:{title:"Terraform",intro:"Infrastructure-as-code should make Proxima configuration repeatable without turning secrets into configuration files.",sections:[["Provider","Configure the integration.","Use the provider and version supported by the actual Proxima distribution you deploy."],["Resources","Model desired state.","Keep tenant, environment and infrastructure configuration declarative where the implementation supports it."],["Secrets","Never commit credentials.","Use your CI or secret-management system for sensitive values rather than hard-coding them in Terraform files."]]},
};
export function Developers(){return <MarketingPage eyebrow="DEVELOPER PLATFORM" title="Build tenant-aware systems with a clear integration model." intro="Start with the quickstart, understand tenant context, then use verification and reference material to integrate Proxima into your stack." links={Object.keys(developerPages).map(k=>`/developers/${k}`)}/>}
export function DeveloperDetail({kind}:{kind:keyof typeof developerPages}){return <ArticlePage eyebrow="DEVELOPER PLATFORM" title={developerPages[kind].title} intro={developerPages[kind].intro} sections={developerPages[kind].sections}/>}

const docs: Record<string,{title:string;intro:string;sections:[string,string,string][]}> = {
  "getting-started":{title:"Getting Started",intro:"A practical path from the tenant model to your first verification run.",sections:[["Prerequisites","Know your tenant boundary.","Before integrating, decide what constitutes a tenant, how identity maps to a tenant and which resources must never cross that boundary."],["Step 1 — Map the request","Find every tenant-aware path.","Identify synchronous API calls, background jobs and internal services that can read or mutate tenant data."],["Step 2 — Introduce tenant context","Make the decision explicit.","Carry tenant scope through the request path and ensure downstream code cannot silently fall back to an unscoped operation."],["Step 3 — Enforce","Place the boundary before protected data.","Use Proxima enforcement and database controls to reject requests whose tenant scope does not match the protected resource."],["Step 4 — Verify","Test both success and failure.","Run same-tenant, cross-tenant and invalid-context scenarios. A useful verification suite proves the negative cases, not only the happy path."],["Step 5 — Review evidence","Understand the result.","Inspect verification and audit evidence before treating the integration as complete."]] },
  "core-concepts":{title:"Core Concepts",intro:"The vocabulary behind the Proxima architecture.",sections:[["Organization","The customer boundary for control-plane configuration.","An organization groups the resources, users, billing context and operational configuration belonging to a customer."],["Tenant","The data-isolation boundary inside an application.","A tenant is the scope whose data must remain isolated from other tenants."],["Tenant context","The requested tenant scope carried through a request.","Context allows the enforcement layer to compare the requested tenant with the protected resource."],["Policy","The rules that determine what is permitted.","Policies provide the explicit decision model used by the enforcement system."],["Verification","A test of the isolation property.","Verification deliberately exercises expected allow and block paths."],["Evidence","The inspectable result.","Evidence gives engineers and security teams a concrete record of what was checked and what happened."]] },
  "api-reference":{title:"API Reference",intro:"Reference material for integrating with the Proxima control plane and protected request model.",sections:[["Authentication","Establish the calling identity.","Use the authentication mechanism supported by your deployed environment. Keep credentials out of browser bundles and source control."],["Tenant context","Pass the intended scope.","Tenant-aware operations must carry enough context for the enforcement boundary to evaluate the request."],["Verification","Run and inspect verification.","Verification operations should report the scenarios tested and the resulting decisions."],["Errors","Diagnose without leaking data.","Clients should distinguish authentication, context, policy and verification failures while avoiding sensitive payload disclosure."]] },
  security:{title:"Security",intro:"How the Proxima model addresses tenant isolation failures.",sections:[["Threat model","Assume the application can make mistakes.","The architecture considers wrong tenant scope, expired context, authorization mistakes and bypassed application checks."],["Defense in depth","Use more than one control.","Application enforcement and database isolation should reinforce one another."],["Verification","Test the dangerous paths.","A secure design is more credible when it can demonstrate that cross-tenant attempts are actually blocked."],["Evidence","Keep the trail.","Record the outcome so a security review can examine what was verified instead of relying on a verbal claim."]] },
  operations:{title:"Operations",intro:"Operate Proxima as infrastructure rather than a hidden library feature.",sections:[["Environments","Separate operational contexts.","Keep development, staging and production configuration distinguishable and avoid accidentally using production credentials during local development."],["Deployments","Know what changed.","Connect deployments to verification so an infrastructure change can be followed by an explicit isolation check."],["Nodes","Understand execution state.","Track the Proxima nodes or execution components that participate in enforcement and verification."],["Incidents","Preserve evidence.","When a failure occurs, capture the verification result, affected environment and relevant events before changing state. "]] },
  troubleshooting:{title:"Troubleshooting",intro:"Diagnose common integration and isolation failures systematically.",sections:[["Cross-tenant request blocked","This is often the expected security result.","Confirm the request's intended tenant and the protected resource. If they differ, the block demonstrates the boundary is working."],["Expired context","The request can no longer prove valid tenant scope.","Refresh or regenerate context using the supported authentication flow, then retry and confirm the resulting decision."],["Verification failure","A test did not produce the expected decision.","Start with the failing scenario, inspect context and policy inputs, then examine evidence to determine where the decision diverged."],["Database enforcement failure","The application and database disagree.","Inspect database policy configuration and the tenant value reaching the database. Do not disable enforcement to make a request succeed."]] },
};
export function Docs(){return <DocsLanding/>}
export function DocsDetail({kind}:{kind:keyof typeof docs}){return <DocsArticle {...docs[kind]}/>}
function DocsLanding(){return <><PageHeader eyebrow="DOCUMENTATION" title="Build, integrate, verify and operate with Proxima." intro="A structured guide to the tenant isolation model, developer integration and operational workflows."/><section className="docs-home public-container"><aside><div className="docs-nav-title">DOCUMENTATION</div>{Object.entries(docs).map(([k,v])=><Link key={k} to={`/docs/${k}`}>{v.title}</Link>)}</aside><div className="docs-home-main"><h2>Start here</h2><p>New to Proxima? Follow Getting Started from tenant modeling through your first verification run.</p><Link className="button button-primary" to="/docs/getting-started">Open Getting Started</Link><div className="docs-cards">{Object.entries(docs).map(([k,v])=><Link to={`/docs/${k}`} key={k}><span>DOCS</span><h3>{v.title}</h3><p>{v.intro}</p><b>Read guide →</b></Link>)}</div></div></section></>}
function DocsArticle({title,intro,sections}:{title:string;intro:string;sections:[string,string,string][]}){return <div className="docs-layout public-container"><aside><div className="docs-nav-title">DOCUMENTATION</div>{Object.entries(docs).map(([k,v])=><Link key={k} to={`/docs/${k}`}>{v.title}</Link>)}</aside><article className="docs-article"><div className="public-eyebrow">DOCUMENTATION</div><h1>{title}</h1><p className="article-intro">{intro}</p>{sections.map(([a,b,c],i)=><section key={a}><div className="article-number">{String(i+1).padStart(2,"0")}</div><div><h2>{a}</h2><h3>{b}</h3><p>{c}</p></div></section>)}<div className="article-footer"><Link to="/docs">Back to Documentation</Link></div></article></div>}

const changes: Record<string,{date:string;title:string;intro:string;sections:[string,string][]}> = {
  "frontend-reconstruction":{date:"October 2026",title:"Public platform reconstruction",intro:"Agata Proxima's public experience is being rebuilt around a real product information architecture rather than a collection of placeholder landing pages.",sections:[["What changed","Public product, developer, documentation, support and company surfaces are now organized as separate destinations with their own information architecture."],["Why","A security infrastructure product needs a public surface that explains the architecture clearly before a user ever enters the authenticated control plane."],["Developer impact","Documentation and developer guides are being structured around integration tasks rather than marketing sections."]] },
  "control-plane-foundation":{date:"October 2026",title:"Control-plane foundation",intro:"The authenticated control plane establishes the workspace model for operating Proxima.",sections:[["What changed","The application surface separates security, tenants, policies, nodes, deployments, verification, audit, team, billing and developer operations."],["Why","Infrastructure needs operational surfaces that map to real responsibilities instead of one generic dashboard."],["Boundary","The control plane remains protected by the existing authentication boundary."]] },
  "authentication-boundary":{date:"October 2026",title:"Authentication boundary",intro:"Public resources and customer control-plane resources now have distinct routing responsibilities.",sections:[["What changed","Public support, documentation and company resources are separated from authenticated customer operations."],["Why","A public information page must never become an implicit shortcut into a customer workspace."],["Security impact","The authenticated `/app/*` surface remains behind RequireAuth."]] },
  "verification-model":{date:"October 2026",title:"Verification model",intro:"Tenant isolation is treated as a property to test rather than a configuration statement to trust.",sections:[["What changed","Verification is modeled around explicit allow and block outcomes."],["Why","Cross-tenant failure modes are exactly the cases a security system must demonstrate it can prevent."],["Evidence","Verification results are intended to become inspectable evidence for operations and security review."]] },
  "api-foundation":{date:"October 2026",title:"API foundation",intro:"The platform API is being organized around explicit identity, tenant context and operational state.",sections:[["What changed","The developer surface now has dedicated authentication, tenant context, verification, API reference and webhook areas."],["Why","Developers need a predictable conceptual model before they can integrate infrastructure safely."],["Next","Reference content will track the actual deployed control-plane capabilities rather than inventing unsupported endpoints."]] },
};
export function Changelog(){return <><PageHeader eyebrow="CHANGELOG" title="Engineering changes behind Agata Proxima." intro="Architecture, security and developer-surface changes documented as the platform evolves."/><Section title="Recent changes"><div className="change-list">{Object.entries(changes).map(([k,c])=><Link to={`/changelog/${k}`} key={k}><span>{c.date}</span><div><h3>{c.title}</h3><p>{c.intro}</p></div><b>Read change →</b></Link>)}</div></Section></>}
export function ChangelogDetail({kind}:{kind:keyof typeof changes}){const c=changes[kind];return <ArticlePage eyebrow={`CHANGELOG / ${c.date}`} title={c.title} intro={c.intro} sections={c.sections.map(([a,b])=>[a,"",b]) as [string,string,string][]}/>}

export function Company(){return <><PageHeader eyebrow="COMPANY" title="Building infrastructure for tenant isolation." intro="Agata Proxima exists to make multi-tenant security boundaries easier to enforce, verify and operate."/><Section title="Why we are building it"><div className="prose-wide"><p>Multi-tenant software depends on isolation everywhere: identity, requests, services, queries, jobs and databases. As systems grow, the number of places that can make a tenant decision grows with them.</p><p>Proxima is built around a different approach: give tenant isolation a dedicated boundary, test it deliberately and retain evidence of the result.</p></div></Section><Section eyebrow="ENGINEERING PRINCIPLES" title="Make important security properties observable."><div className="three-columns"><article><h3>Explicit boundaries</h3><p>Security decisions should have a defined place in the architecture.</p></article><article><h3>Verification</h3><p>Important properties should be tested against both expected and adversarial paths.</p></article><article><h3>Operational clarity</h3><p>Engineers should be able to understand what happened without reconstructing it from scattered logs.</p></article></div></Section><Section title="Talk to us"><div className="prose-wide"><p>Questions about the product, engineering direction or partnerships?</p><Link className="button button-primary" to="/contact">Contact Agata Proxima</Link></div></Section></>}

export function Trust(){return <><PageHeader eyebrow="TRUST CENTER" title="Understand the controls behind the platform." intro="Trust is about knowing how the system is designed, what controls exist and what can actually be demonstrated."/><Section title="Trust areas"><div className="link-grid">{[["Security architecture","/security","Tenant isolation, identity and defense in depth."],["Verification","/product/verification","How expected allow and block behavior is tested."],["Evidence","/product/evidence","How operational results become inspectable evidence."],["Documentation","/docs/security","Technical security model and troubleshooting."],["Status","/status","Current service and incident information."],["Contact","/contact","Security and operational contact paths."]].map(([a,b,c])=><Link to={b} key={a}><strong>{a}</strong><span>{c}</span></Link>)}</div></Section><Section title="What we will not claim"><div className="prose-wide"><p>We will not use the trust center to imply certifications, compliance programs, uptime guarantees or security controls that have not been established and documented.</p></div></Section></>}

export function Status(){return <><PageHeader eyebrow="STATUS" title="Agata Proxima service status." intro="A clear place to understand the operational state of the platform and review incidents."/><Section title="Current services"><div className="status-list">{["Control Plane","Proxima Engine","Verification","API","Documentation"].map(s=><div key={s}><span className="status-dot"/><strong>{s}</strong><span>Status feed pending</span></div>)}</div></Section><Section title="Incident history"><div className="empty-state"><strong>Live service telemetry is not connected to this public surface yet.</strong><p>This page is deliberately not presenting simulated uptime data. When the operational status feed is connected, this section will show current service state, incident timelines, impact, resolution and follow-up actions.</p></div></Section></>}

export function Contact(){return <><PageHeader eyebrow="CONTACT" title="Talk to the right Agata Proxima team." intro="Choose the reason for contacting us so your request reaches the right workflow."/><Section title="Contact paths"><div className="contact-grid">{[["Sales","Questions about plans, deployment and enterprise requirements.","/pricing"],["Technical","Integration and architecture questions.","/developers"],["Security","Security reports and responsible disclosure.","/security"],["Support","Troubleshooting and product guidance.","/support"],["General","Company, partnerships and other inquiries.","/company"]].map(([a,b,c])=><Link to={c} key={a}><strong>{a}</strong><p>{b}</p><span>Open related resource →</span></Link>)}</div></Section><Section title="Before contacting support"><div className="prose-wide"><p>Include the environment, operation, error message and the steps that reproduce the problem. Never send API keys, passwords or other secrets in a support request.</p></div></Section></>}

const faqs=[
["What is Agata Proxima?","Agata Proxima is tenant isolation infrastructure designed to give multi-tenant systems an explicit enforcement and verification boundary."],
["Is Proxima an authentication provider?","No. Authentication establishes identity. Proxima focuses on tenant-aware enforcement and verification around protected resources."],
["What happens when a request crosses tenants?","The intended model is to block the request rather than allow an application convention to silently decide that the access is acceptable."],
["What happens when tenant context expires?","Expired or invalid context should fail closed. The request should not fall back to an unscoped operation."],
["Why is verification separate from enforcement?","Enforcement makes the decision. Verification tests whether the expected decision actually occurs."],
["Where do I start integrating?","Start with the Developer Platform quickstart, then read Tenant Context and Verification."],
["Where do I get help?","Use the public Support Center for troubleshooting and the authenticated control-plane support area for customer operational support."],
["Does public Support require an account?","No. Public documentation and support resources are intentionally available without entering the customer control plane."],
];
export function FAQ(){return <><PageHeader eyebrow="FAQ" title="Answers to common Agata Proxima questions." intro="Product, security, developer and support questions in one place."/><Section title="Frequently asked questions"><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></Section><Section title="Need more detail?"><div className="inline-links"><Link to="/docs">Documentation</Link><Link to="/developers">Developer Platform</Link><Link to="/support">Support Center</Link></div></Section></>}

const supportCategories=[
["Getting started","Installation, first tenant, authentication and first verification.",["Installation","First tenant","Authentication","First verification"]],
["Tenant isolation","Diagnose tenant context, cross-tenant blocks and enforcement.",["Cross-tenant request blocked","Tenant context rejected","Expired tenant context","Isolation verification failed"]],
["Developer platform","API, SDK, CLI, webhooks and infrastructure-as-code.",["API integration","SDK setup","CLI","Webhooks","Terraform"]],
["Operations","Deployments, nodes, environments and operational failures.",["Deployment issue","Node issue","Environment configuration","Verification after deployment"]],
["Account & billing","Organizations, team access, plans and invoices.",["Organization access","Team members","Plans","Billing"]],
["Security","Security questions and responsible disclosure.",["Security report","Security architecture","Responsible disclosure"]],
];
export function Support(){return <><PageHeader eyebrow="SUPPORT CENTER" title="Find the answer before you open a ticket." intro="Troubleshoot integrations, tenant isolation, developer tooling, operations and account questions through focused support paths."/><section className="support-search public-container"><input placeholder="Search support topics…" aria-label="Search support topics"/><span>Search documentation and troubleshooting guides</span></section><Section title="What are you trying to solve?"><div className="support-grid">{supportCategories.map(([title,desc,items])=><article key={title as string}><div><span className="public-eyebrow">SUPPORT</span><h3>{title as string}</h3><p>{desc as string}</p></div><ul>{(items as string[]).map(item=><li key={item}><Link to={`/support/${supportSlug(title as string)}/${slug(item)}`}>{item} →</Link></li>)}</ul></article>)}</div></Section><Section title="Still need help?"><div className="prose-wide"><p>Gather the environment, operation, error and reproduction steps. Do not include secrets.</p><Link className="button button-primary" to="/contact">Contact Agata Proxima</Link></div></Section></>}
function supportSlug(s:string){return s.toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function slug(s:string){return supportSlug(s)}
const supportArticles: Record<string,{title:string;category:string;intro:string;steps:string[]}> = {};
for(const [title,,items] of supportCategories){for(const item of items as string[]){const key=`${supportSlug(title as string)}/${slug(item)}`;supportArticles[key]={title:item,category:title as string,intro:`Troubleshooting guidance for ${item.toLowerCase()}.`,steps:["Confirm the environment and the operation you were attempting.","Record the exact error or unexpected result without including credentials or secrets.","Check the related documentation and verify tenant context, authentication and policy inputs.","Reproduce the issue with the smallest possible request and compare it with the expected allow or block decision.","If the problem remains, contact Agata Proxima with the environment, timestamp, reproduction steps and non-sensitive diagnostics."]};}}
export function SupportArticle(){const {category,article}=useParams();const key=`${category}/${article}`;const a=supportArticles[key]??{title:"Support article",category:"Support",intro:"The requested support article could not be resolved.",steps:["Return to the Support Center and choose a supported topic."]};return <ArticlePage eyebrow={`SUPPORT / ${a.category.toUpperCase()}`} title={a.title} intro={a.intro} sections={a.steps.map((s,i)=>[`${i+1}. ${["Confirm","Capture","Check","Reproduce","Escalate"][i]??"Next step"}`,"Recommended action",s]) as [string,string,string][]}/>}

export function Terms(){return <Legal title="Terms of Service" updated="October 2026" sections={[["Agreement","These terms govern access to and use of Agata Proxima services, documentation and public resources. By using a service, you agree to use it only for lawful and authorized purposes."],["Accounts and access","Keep account credentials secure, maintain accurate account information and restrict access to authorized users. You are responsible for activity performed through your account and organization permissions."],["Acceptable use","Do not use Agata Proxima to compromise systems, bypass security controls, access data without authorization, interfere with service operation or test security boundaries against systems you do not control."],["Customer responsibilities","Customers remain responsible for their applications, tenant model, data, credentials and configuration. Proxima provides enforcement and verification infrastructure; it does not make an application's authorization decisions correct by itself."],["Service availability and changes","Infrastructure products evolve. Features, integrations, limits and documentation may change. Where a change materially affects a contracted service, applicable customer agreements govern notice and transition requirements."],["Security reports","Report suspected security issues through the Security or Contact paths and avoid publicly disclosing sensitive details before the issue can be investigated."],["Intellectual property","Agata Proxima materials, software and branding remain subject to their applicable licenses or ownership terms. Customer data and customer-owned materials remain the customer's responsibility."],["Contact","Questions about these terms can be directed through the Contact page."]]}/>
export function Privacy(){return <Legal title="Privacy Policy" updated="October 2026" sections={[["Scope","This policy describes how Agata Proxima may process personal information when you use the public website, create an account, contact the team or use the service."],["Information we handle","Depending on the interaction, information may include identity and contact details, organization membership, authentication metadata, support requests, billing context, operational events and technical diagnostics."],["How information is used","Information is used to provide and secure the service, authenticate users, enforce organization access, respond to support requests, operate billing and integrations, investigate incidents and improve reliability."],["Public contact and support","Public contact and support submissions are stored so the team can respond and maintain an operational record. Do not submit passwords, API keys, private tokens or other secrets through public forms."],["Security","Access controls, server-side credential handling, database controls and operational safeguards are used to protect information. No internet service can guarantee absolute security."],["Retention","Retention periods depend on the type of information, operational requirements, security investigations, customer agreements and applicable legal obligations."],["Service providers","Agata Proxima may use infrastructure and integration providers needed to host, operate, secure and bill the service. The applicable production environment should maintain the current provider and subprocessors record."],["Your questions and requests","For privacy questions or requests, use the Contact page and identify the request as a privacy inquiry."]]}/>
function Legal({title,updated,sections}:{title:string;updated:string;sections:[string,string][]}){return <><PageHeader eyebrow="LEGAL" title={title} intro={`Last updated: ${updated}.`}/><article className="legal-document public-container"><aside><span>ON THIS PAGE</span>{sections.map(([a])=><a href={`#${slug(a)}`} key={a}>{a}</a>)}</aside><div>{sections.map(([a,b])=><section id={slug(a)} key={a}><h2>{a}</h2><p>{b}</p></section>)}</div></article></>}

function MarketingPage({eyebrow,title,intro,links}:{eyebrow:string;title:string;intro:string;links:string[]}){return <><PageHeader eyebrow={eyebrow} title={title} intro={intro}/><Section title="How it works"><Architecture/></Section><Section eyebrow="EXPLORE" title="Go deeper"><div className="link-grid">{links.map(path=><Link to={path} key={path}><strong>{path.split("/").filter(Boolean).slice(-1)[0].replaceAll("-"," ")}</strong><span>Explore this part of the Agata Proxima architecture →</span></Link>)}</div></Section><Section dark title="A boundary you can explain to your team."><div className="prose-dark"><p>Proxima is designed around a straightforward operational story: establish tenant context, enforce the boundary, verify expected behavior and retain evidence.</p><Link to="/docs/getting-started">Read the implementation guide →</Link></div></Section></>}
function ArticlePage({eyebrow,title,intro,sections}:{eyebrow:string;title:string;intro:string;sections:[string,string,string][]}){return <><PageHeader eyebrow={eyebrow} title={title} intro={intro}/><article className="long-article public-container">{sections.map(([a,b,c],i)=><section key={a}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{a}</h2>{b&&<h3>{b}</h3>}<p>{c}</p></div></section>)}<div className="article-links"><Link to="/docs">Documentation</Link><Link to="/support">Support</Link><Link to="/contact">Contact</Link></div></article></>}
